Adding magician components
GOlivierNation/math-magicians pull request #2
Opened 2022-05-31 20:43 UTC by GOlivierNation

**### What is Done:**
**************************
    Delete all the boilerplate from CRA (text, images, styles).
    Create a directory called components.
    Inside components, create a new Calculator.js file.

    **In Calculator.js, create a React component that matches this design:**
    Don't add any extra design.
    Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
    Use class based components (All components should be class-based).
    Once the Calculator is ready, import it and use it in your main component (App.js).
    Test it in the browser; it should render without problems.

2022-05-31 21:24 UTC, AmaduKamara requested changes
# Staus: Required Changes ♻️♻️♻️ 

Hi @GOlivierNation,

![AlonzoLeroneThisCloseGIF (3)](https://user-images.githubusercontent.com/50941074/171286798-9af56c05-d557-45aa-8b50-fc3b8fc60c29.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Correct use of Github workflow
✅ No linter error
✅ README is okay

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-05-31 21:24 UTC, AmaduKamara commented on src/Calculator.js
> +
- [ ] Kindly make this component a class-based component as required by the project requirements. For this project, you are required to make use of React class components for all your components.
- [ ] Also, I noticed the `Calculator.js` component is outside of the components directory. Kindly move it to the components directory and then import it from that directory into the AApp.js where you making use of it. 👍 

**Please Read the Screenshot From Your Project Requirements below**

![image](https://user-images.githubusercontent.com/50941074/171285327-d0022382-d9dd-4ad8-a2bb-51154c49bc71.png)

2022-05-31 21:24 UTC, AmaduKamara commented on src/Calculator.js
> +      <Header />
# Optional Change

- [ ] It would be nice if you just call the `Header` component in the `App.js` component instead of calling it in the other three components whenever you need it. Try calling it in the App component above the `<Routes>` and it will be available for all pages. 👍

2022-06-01 08:01 UTC, Kingstalux approved these changes
Hi @GOlivierNation,
# Status: Approved ✔️ ✔️ ✔️ 
 
![169317575-075e3122-7a58-4969-9611-637f7e3018db](https://user-images.githubusercontent.com/85113567/171356699-442853fa-dacc-4b80-ae25-2955db25ef93.gif)

## Highlights 👏 
✅ App works as expected 🔥 
✅ Linters are passing 👍 
✅ Professional README file 💯
 
Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 08:24 UTC, merged